import Foundation
import Testing
@testable import OpenClaw

struct GatewayLaunchAgentManagerTests {
    @Test func `attach only runtime override does not uninstall gateway launch agent`() throws {
        let dir = FileManager().temporaryDirectory
            .appendingPathComponent("openclaw-attach-only-\(UUID().uuidString)", isDirectory: true)
        let marker = dir.appendingPathComponent("disable-launchagent")
        try FileManager().createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager().removeItem(at: dir) }
        defer {
            GatewayLaunchAgentManager.setTestingDisableLaunchAgentMarkerURL(nil)
            GatewayLaunchAgentManager.setTestingInterceptDaemonCommands(false)
            GatewayLaunchAgentManager.clearTestingDaemonCommandCalls()
        }

        GatewayLaunchAgentManager.setTestingDisableLaunchAgentMarkerURL(marker)
        GatewayLaunchAgentManager.setTestingInterceptDaemonCommands(true)
        GatewayLaunchAgentManager.clearTestingDaemonCommandCalls()

        let error = GatewayLaunchAgentManager.applyAttachOnlyRuntimeOverride()

        #expect(error == nil)
        #expect(FileManager().fileExists(atPath: marker.path))
        #expect(GatewayLaunchAgentManager.testingDaemonCommandCallsSnapshot().isEmpty)
    }

    @Test func `launch agent plist snapshot parses args and env`() throws {
        let url = FileManager().temporaryDirectory
            .appendingPathComponent("openclaw-launchd-\(UUID().uuidString).plist")
        let plist: [String: Any] = [
            "ProgramArguments": ["openclaw", "gateway", "--port", "18789", "--bind", "loopback"],
            "EnvironmentVariables": [
                "OPENCLAW_GATEWAY_TOKEN": " secret ",
                "OPENCLAW_GATEWAY_PASSWORD": "pw",
            ],
        ]
        let data = try PropertyListSerialization.data(fromPropertyList: plist, format: .xml, options: 0)
        try data.write(to: url, options: [.atomic])
        defer { try? FileManager().removeItem(at: url) }

        let snapshot = try #require(LaunchAgentPlist.snapshot(url: url))
        #expect(snapshot.port == 18789)
        #expect(snapshot.bind == "loopback")
        #expect(snapshot.token == "secret")
        #expect(snapshot.password == "pw")
    }

    @Test func `launch agent plist snapshot parses generated env wrapper file`() throws {
        let dir = FileManager().temporaryDirectory
            .appendingPathComponent("openclaw-launchd-\(UUID().uuidString)", isDirectory: true)
        let envDir = dir.appendingPathComponent("service-env", isDirectory: true)
        let plistURL = dir.appendingPathComponent("ai.openclaw.gateway.plist")
        let wrapperURL = envDir.appendingPathComponent("ai.openclaw.gateway-env-wrapper.sh")
        let envURL = envDir.appendingPathComponent("ai.openclaw.gateway.env")
        try FileManager().createDirectory(at: envDir, withIntermediateDirectories: true)
        defer { try? FileManager().removeItem(at: dir) }

        try """
        # Generated by OpenClaw. Do not edit while the gateway service is installed.
        export OPENCLAW_GATEWAY_TOKEN=' file-token '
        export OPENCLAW_GATEWAY_PASSWORD='file-password'

        """.write(to: envURL, atomically: true, encoding: .utf8)
        let plist: [String: Any] = [
            "ProgramArguments": [
                wrapperURL.path,
                envURL.path,
                "openclaw",
                "gateway",
                "--port",
                "18789",
                "--bind",
                "loopback",
            ],
            "EnvironmentVariables": [
                "OPENCLAW_GATEWAY_TOKEN": "inline-token",
                "PATH": "/usr/bin",
            ],
        ]
        let data = try PropertyListSerialization.data(fromPropertyList: plist, format: .xml, options: 0)
        try data.write(to: plistURL, options: [.atomic])

        let snapshot = try #require(LaunchAgentPlist.snapshot(url: plistURL))
        #expect(snapshot.programArguments == ["openclaw", "gateway", "--port", "18789", "--bind", "loopback"])
        #expect(snapshot.environment["OPENCLAW_GATEWAY_TOKEN"] == " file-token ")
        #expect(snapshot.environment["OPENCLAW_GATEWAY_PASSWORD"] == "file-password")
        #expect(snapshot.environment["PATH"] == "/usr/bin")
        #expect(snapshot.token == "file-token")
        #expect(snapshot.password == "file-password")
    }

    @Test func `launch agent plist snapshot keeps custom wrapper arguments`() throws {
        let dir = FileManager().temporaryDirectory
            .appendingPathComponent("openclaw-launchd-\(UUID().uuidString)", isDirectory: true)
        let plistURL = dir.appendingPathComponent("ai.openclaw.gateway.plist")
        let wrapperURL = dir.appendingPathComponent("custom-env-wrapper.sh")
        let wrapperArgURL = dir.appendingPathComponent("custom.env")
        try FileManager().createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager().removeItem(at: dir) }

        try "export OPENCLAW_GATEWAY_TOKEN='wrong-token'\n".write(
            to: wrapperArgURL,
            atomically: true,
            encoding: .utf8)
        let programArguments = [
            wrapperURL.path,
            wrapperArgURL.path,
            "openclaw",
            "gateway",
            "--port",
            "18789",
        ]
        let plist: [String: Any] = [
            "ProgramArguments": programArguments,
            "EnvironmentVariables": [
                "OPENCLAW_GATEWAY_TOKEN": "inline-token",
            ],
        ]
        let data = try PropertyListSerialization.data(fromPropertyList: plist, format: .xml, options: 0)
        try data.write(to: plistURL, options: [.atomic])

        let snapshot = try #require(LaunchAgentPlist.snapshot(url: plistURL))
        #expect(snapshot.programArguments == programArguments)
        #expect(snapshot.token == "inline-token")
    }

    @Test func `launch agent plist snapshot allows missing bind`() throws {
        let url = FileManager().temporaryDirectory
            .appendingPathComponent("openclaw-launchd-\(UUID().uuidString).plist")
        let plist: [String: Any] = [
            "ProgramArguments": ["openclaw", "gateway", "--port", "18789"],
        ]
        let data = try PropertyListSerialization.data(fromPropertyList: plist, format: .xml, options: 0)
        try data.write(to: url, options: [.atomic])
        defer { try? FileManager().removeItem(at: url) }

        let snapshot = try #require(LaunchAgentPlist.snapshot(url: url))
        #expect(snapshot.port == 18789)
        #expect(snapshot.bind == nil)
    }
}
